### ISSUE TITLE
String and NoneType can't compare

### ISSUE THREAD

**Issue by tac0x2a** [tac0x2a/grebe#25]
```
[ERROR] 2020-07-19 15:58:25,265 | ./grebe.py(L113) | '<' not supported between instances of 'str' and 'NoneType',
Traceback (most recent call last):,
  File "./grebe.py", line 104, in callback,
    (columns, types, values_list) = d2c.data_string2type_value(payload, specified_types=spec_types),
  File "/usr/local/lib/python3.8/site-packages/lakeweed/clickhouse.py", line 56, in data_string2type_value,
    (correct_type, converter) = __type_map(current_type, new_col),
  File "/usr/local/lib/python3.8/site-packages/lakeweed/clickhouse.py", line 220, in __type_map,
    from_to = "".join(sorted([from_, to])),
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

**Comment by tac0x2a** [comment]
Fix in v1.0.4 release
